import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Content from './Content'
import CommentBlog from './commentBlog'
import Footer from './footer'
import DenemelikNav from './denemeliknav'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tinder | Yeni İnsanlarla Tanış,Buluş,Sohbet et</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://logos-world.net/wp-content/uploads/2020/09/Tinder-Emblem.png" />
      </Head>
        <DenemelikNav/>
            <div>
                <div className={styles.kafa}/>
                <Content/>
            </div>
        <CommentBlog/>
        <Footer/>
    </div>
  )
}

// build işlemleri araştırıldı
