import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './header'
import Content from './Content'
import CommentBlog from './commentBlog'
import Footer from './footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <div>
                <div className={styles.kafa}/>
                <Header />
                <Content/>
            </div>
        <CommentBlog/>
        <Footer/>
    </div>
  )
}
